### PR TITLE
some improvements

### PR DESCRIPTION
**Pull request by volkov-andrey**
- split hooks
- rename some things in hooks (do 1 codestyle in hooks)
- rename menu_framework, custom_menu_framework to gui
- now gui::button returns true on press
- second button implementation

### CODE REVIEW

**Comment by r4v10l1** [comment]
The only problem I see at the moment is that the `bool gui::button()` you changed acts as a switch, which could be a good concept, but not what I was trying to do.

The idea (which I did not manage to implement) was to pass a function address or something similar as parameters for the `void custom_menu_framework::button()` function that was used before, and when pressing the button, that function would execute.

It looks like a simple concept but I could not do it, so I just used a "function id" and then a `switch(id)` to check what function to use.

**Comment by volkov-andrey** [comment]
just it will be easy to understand for guys that try to make some things related to button after imgui, i can do it as you want

**Comment by r4v10l1** [comment]
As I said you can keep the feature, but the button should be used to execute an action (for example releasing the cheat, etc.)

**Comment by volkov-andrey** [comment]
can you send your telegram?

**Comment by r4v10l1** [comment]
You can send me a discord message at `8dcc30b468f4#7423`

**Pull request merged**
