### PR TITLE
Add panorama, fix naming to proper casing, add last_command function to prediction

### PR DESCRIPTION
**Pull request by coffin1337**

### CODE REVIEW

**Review by r4v10l1 — APPROVED** [review]

**Comment by r4v10l1** [comment]
~~MinionWare~~ WeedWare soon... 😈 

Thank you for your contribution!

**Comment by Patoke** [comment]
the panorama classes are incomplete, might push full ones later
also, atleast credit the entire TeamSCALEFORM and not just parallel, there was more people working on this than u think (btw u didn't add last_command to prediction, u made a function that grabs it in the entity class, last_command is just used in prediction, Kind Regards :3)

**Comment by r4v10l1** [comment]
> the panorama classes are incomplete, might push full ones later also, atleast credit the entire TeamSCALEFORM and not just parallel, there was more people working on this than u think (btw u didn't add last_command to prediction, u made a function that grabs it in the entity class, last_command is just used in prediction, Kind Regards :3)

Patoke has spoken. Float manifest yourself.

**Comment by r4v10l1** [comment]
Related to #52

**Pull request merged**
